# Generated by Django 6.0.7 on 2026-08-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Commodity Category', 'verbose_name_plural': 'Commodity Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Facility Stock Level', 'verbose_name_plural': 'Facility Stock Levels'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Medical Commodity', 'verbose_name_plural': 'Medical Commodities'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory_items', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5, verbose_name='Minimum Safe Stock'),
        ),
    ]
