# Generated by Django 5.1.3 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('patient_footfall', models.PositiveIntegerField(default=0)),
                ('beds_total', models.PositiveIntegerField(default=0)),
                ('beds_occupied', models.PositiveIntegerField(default=0)),
                ('doctors_scheduled', models.PositiveIntegerField(default=0)),
                ('doctors_present', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='warehouses.warehouse', verbose_name='Health Facility')),
            ],
            options={
                'verbose_name': 'Facility Daily Stats',
                'verbose_name_plural': 'Facility Daily Stats',
                'ordering': ['-date'],
                'unique_together': {('warehouse', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FacilityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('understaffed', 'Understaffed'), ('low_footfall', 'Low Footfall'), ('overcrowded', 'Overcrowded'), ('stockout_risk', 'Stock-Out Risk'), ('custom', 'Custom')], max_length=30)),
                ('message', models.TextField(help_text='Gemma-generated or manually entered narrative')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_alerts', to='warehouses.warehouse', verbose_name='Health Facility')),
            ],
            options={
                'verbose_name': 'Facility Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='facilitydailystats',
            index=models.Index(fields=['warehouse', 'date'], name='facility_op_warehou_13c9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityalert',
            index=models.Index(fields=['warehouse', 'resolved'], name='facility_op_warehou_40354f_idx'),
        ),
    ]
