# Generated by Django 6.0.7 on 2026-08-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility_ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facilityalert',
            new_name='facility_op_warehou_6324e4_idx',
            old_name='facility_op_warehou_40354f_idx',
        ),
        migrations.RenameIndex(
            model_name='facilitydailystats',
            new_name='facility_op_warehou_7021bf_idx',
            old_name='facility_op_warehou_13c9c0_idx',
        ),
    ]
