# Generated by Django 5.1.3 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='warehouse',
            field=models.ForeignKey(
                blank=True,
                help_text='Facility assignment for Tier-2 scoped dashboards and AI endpoints.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_staff',
                to='warehouses.warehouse',
            ),
        ),
    ]
