# Generated by Django 6.0.7 on 2026-08-01 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('vat_category', models.CharField(choices=[('STANDARD', 'Standard Rate (16%)'), ('ZERO', 'Zero Rated (0%)'), ('EXEMPT', 'Exempt')], default='STANDARD', max_length=20)),
            ],
            options={
                'verbose_name': 'Commodity Category',
                'verbose_name_plural': 'Commodity Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='EAN-13, UPC, or custom barcode', max_length=50, unique=True)),
                ('product_type', models.CharField(choices=[('PHYSICAL', 'Physical Product'), ('DIGITAL', 'Digital Product'), ('SERVICE', 'Service')], default='PHYSICAL', max_length=10)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Bulk purchase price', max_digits=10, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=5, verbose_name='Minimum Safe Stock')),
                ('is_active', models.BooleanField(default=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.category')),
            ],
            options={
                'verbose_name': 'Medical Commodity',
                'verbose_name_plural': 'Medical Commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inventory_items', to='warehouses.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.product')),
            ],
            options={
                'verbose_name': 'Facility Stock Level',
                'verbose_name_plural': 'Facility Stock Levels',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Optimal size: 800x800px', upload_to='products/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suppliers.product')),
            ],
            options={
                'ordering': ['-is_primary'],
            },
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='suppliers_p_sku_4d0f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='suppliers_p_barcode_cb93c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='suppliers_p_categor_f4077d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'warehouse'], name='suppliers_i_product_f6f751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse')},
        ),
    ]
